name: Feature request
description: Suggest an idea for this project
title: "feat: "
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        **Note**: GitHub issues are used for bug reports and feature requests. For support questions, please use [our forum](https://discourse.ubuntu.com/c/lxd/).

        Please fill out the fields below to the best of your ability. Doing so will help us understand your feature request.

  - type: checkboxes
    id: ack_searched
    attributes:
      label: Please confirm
      options:
        - label: I have searched existing issues to check if an issue already exists for my feature request.
          required: true

  - type: textarea
    id: related_problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. "I'm always frustrated when..."
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
